[package]
name = "static_rd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lru_stack = { path = "../stack_alg_sim/lru_stack"}
hist = { path = "../stack_alg_sim/hist" }
v3pluss = { path = "../v3pluss" }

